/**
 * Fallback activity table.
 *
 * Generated by scripts/derive-activities.mjs. Do not edit by hand.
 *
 * The app derives this list from the live manifest on every visit and only
 * falls back to this snapshot when bungie.net cannot be reached. Keeping it
 * committed means the site still renders something sensible when the API is
 * down, without making the list the source of truth.
 *
 * Manifest version: 244213.26.06.29.2000-1-bnet.65583
 * Derived: 14 raids, 9 dungeons, 4 pantheon encounters
 */

import type { ActivityGroup } from './types';

export const FALLBACK_MANIFEST_VERSION = '244213.26.06.29.2000-1-bnet.65583';

export const FALLBACK_ACTIVITIES: ActivityGroup[] = [
  {
    name: 'Crota\'s End',
    category: 'raid',
    tiers: ['Legend', 'Master', 'Normal', 'Standard'],
    hashes: [107319834, 156253568, 1507509200, 1566480315, 4179289725]
  },
  {
    name: 'Crown of Sorrow',
    category: 'raid',
    tiers: ['Normal'],
    hashes: [960175301, 3333172150]
  },
  {
    name: 'Deep Stone Crypt',
    category: 'raid',
    tiers: ['Standard'],
    hashes: [910380154]
  },
  {
    name: 'Garden of Salvation',
    category: 'raid',
    tiers: ['Standard'],
    hashes: [1042180643]
  },
  {
    name: 'King\'s Fall',
    category: 'raid',
    tiers: ['Expert', 'Master', 'Standard'],
    hashes: [1063970578, 1374392663, 3257594522]
  },
  {
    name: 'Last Wish',
    category: 'raid',
    tiers: ['Level 55', 'Level 58', 'Normal', 'Standard'],
    hashes: [1661734046, 2122313384, 2214608156, 2214608157]
  },
  {
    name: 'Leviathan',
    category: 'raid',
    tiers: ['Normal', 'Prestige', 'Standard'],
    hashes: [89727599, 287649202, 417231112, 508802457, 757116822, 771164842, 1685065161, 1699948563, 1800508819, 1875726950, 2449714930, 2693136600, 2693136601, 2693136602, 2693136603, 2693136604, 2693136605, 3446541099, 3857338478, 3879860661, 3912437239, 3916343513, 4039317196, 4206123728]
  },
  {
    name: 'Leviathan, Eater of Worlds',
    category: 'raid',
    tiers: ['Normal', 'Prestige', 'Standard'],
    hashes: [809170886, 2164432138, 3089205900]
  },
  {
    name: 'Leviathan, Spire of Stars',
    category: 'raid',
    tiers: ['Normal', 'Prestige', 'Standard'],
    hashes: [119944200, 3004605630, 3213556450]
  },
  {
    name: 'Root of Nightmares',
    category: 'raid',
    tiers: ['Master', 'Standard'],
    hashes: [2381413764, 2918919505]
  },
  {
    name: 'Salvation\'s Edge',
    category: 'raid',
    tiers: ['Master', 'Standard'],
    hashes: [940375169, 1541433876, 2192826039, 4129614942]
  },
  {
    name: 'Scourge of the Past',
    category: 'raid',
    tiers: ['Standard'],
    hashes: [548750096, 2812525063]
  },
  {
    name: 'Vault of Glass',
    category: 'raid',
    tiers: ['Challenge Mode', 'Master', 'Standard'],
    hashes: [1485585878, 3022541210, 3881495763]
  },
  {
    name: 'Vow of the Disciple',
    category: 'raid',
    tiers: ['Master', 'Standard'],
    hashes: [1441982566, 2906950631, 3889634515]
  },
  {
    name: 'The Pantheon: Atraks Sovereign',
    category: 'pantheon',
    tiers: ['Standard'],
    hashes: [4169648179]
  },
  {
    name: 'The Pantheon: Nezarec Sublime',
    category: 'pantheon',
    tiers: ['Standard'],
    hashes: [4169648182]
  },
  {
    name: 'The Pantheon: Oryx Exalted',
    category: 'pantheon',
    tiers: ['Standard'],
    hashes: [4169648176]
  },
  {
    name: 'The Pantheon: Rhulk Indomitable',
    category: 'pantheon',
    tiers: ['Standard'],
    hashes: [4169648177]
  },
  {
    name: 'Duality',
    category: 'dungeon',
    tiers: ['Master', 'Standard'],
    hashes: [2823159265, 3012587626]
  },
  {
    name: 'Equilibrium',
    category: 'dungeon',
    tiers: ['Contest', 'Standard'],
    hashes: [1754635208, 2727361621]
  },
  {
    name: 'Ghosts of the Deep',
    category: 'dungeon',
    tiers: ['Master', 'Standard'],
    hashes: [313828469, 2716998124]
  },
  {
    name: 'Grasp of Avarice',
    category: 'dungeon',
    tiers: ['Master', 'Standard'],
    hashes: [1112917203, 4078656646]
  },
  {
    name: 'Pit of Heresy',
    category: 'dungeon',
    tiers: ['Expert', 'Legend', 'Master', 'Normal', 'Standard'],
    hashes: [785700673, 785700678, 1375089621, 2559374368, 2559374374, 2559374375, 2582501063]
  },
  {
    name: 'Prophecy',
    category: 'dungeon',
    tiers: ['Standard'],
    hashes: [1077850348, 4148187374]
  },
  {
    name: 'Spire of the Watcher',
    category: 'dungeon',
    tiers: ['Master', 'Standard'],
    hashes: [1262462921, 2296818662]
  },
  {
    name: 'The Shattered Throne',
    category: 'dungeon',
    tiers: ['Standard'],
    hashes: [2032534090]
  },
  {
    name: 'Warlord\'s Ruin',
    category: 'dungeon',
    tiers: ['Master', 'Standard'],
    hashes: [2004855007, 2534833093]
  }
];
